source "https://rubygems.org"

gem 'sinatra'
gem 'sass'
gem 'slim'
gem 'dm-core'
gem 'dm-migrations'
gem "thin"

#PRODUCTION
gem "pg",                  :group => :production
gem "dm-postgres-adapter", :group => :production

#DEVELOPMENT
gem "dm-sqlite-adapter",   :group => :development
gem 'sinatra-contrib',     :group => :development
